services:
  - type: web
    name: brh-lab
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

